name = "gotbilled"
main = "src/worker.ts"
compatibility_date = "2024-09-25"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "gotbilled-db"
database_id = "935594bc-e5b9-4102-8ee6-26f6fe955930"

[[kv_namespaces]]
binding = "CACHE"
id = "ce40d4a2eb984d9d8efe68ac6b8c414f"

[[queues.producers]]
queue = "gotbilled-submissions"
binding = "SUBMISSIONS_QUEUE"

[[queues.consumers]]
queue = "gotbilled-submissions"
max_batch_size = 50
max_batch_timeout = 5
max_concurrency = 20
